# Sentiment analysis model using PySpark
The task is to create a sentiment analysis model using PySpark that can classify movie reviews as either positive or negative. The input data consists of a large dataset of movie reviews that have been labeled with a sentiment score (positive or negative). The goal is to build a binary classification model that can accurately predict the sentiment of a new movie review that it has not seen before. 

The sentiment analysis model will use natural language processing (NLP) techniques to preprocess the text data, including tokenization, stopword removal, count vectorization, and TF-IDF. It will then use different machine learning algorithms, such as logistic regression, SVM, or a multilayer perceptron, to train a binary classifier on the preprocessed text features. The model will be evaluated using metrics precision, recall, F1 score, and confusion matrix. 

In the end, we show how feature selection techniques such as Chi-Square can be included in the preprocessing pipeline, and we build a logistic regression model again.

In [1]:
# import findspark
# findspark.init()
from pyspark import SparkContext
from pyspark.sql import SparkSession
sc = SparkContext.getOrCreate()
spark = SparkSession.builder.getOrCreate()

In [2]:
import numpy as np
from pyspark.sql import functions as F

# Data preprocessing

In [3]:
tFile="data\IMDB Dataset.csv.bz2"
df0 = spark.read.csv(tFile,header=True)
df0.show(10)

+--------------------+---------+
|                text|sentiment|
+--------------------+---------+
|One of the other ...| positive|
|A wonderful littl...| positive|
|I thought this wa...| positive|
|Basically there's...| negative|
|Petter Mattei's L...| positive|
|Probably my all-t...| positive|
|I sure would like...| positive|
|This show was an ...| negative|
|Encouraged by the...| negative|
|If you like origi...| positive|
+--------------------+---------+
only showing top 10 rows

In [4]:
#Sample the data for faster model training (use the full dataset in reality)
df0 = df0.sample(0.25, seed=200)

In [5]:
# Convert sentiment to numbers positive =1, negative =0
df0 = df0.withColumn("label", F.when(F.col("sentiment")=="positive",1).otherwise(0)).cache()

In [6]:
df0.show(10, truncate=False)

+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+-----+
|text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |sentiment|label|
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+-----+
|One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |positive |1    |

In [7]:
# Remove html tags from text
df0 = df0.withColumn("text_c", F.regexp_replace(F.col("text"), r'<[^>]+>', ""));
# Remove non-letters
df0 = df0.withColumn("text_c", F.regexp_replace("text_c", r"[^a-zA-Z ]", ""))
# Remove words 1, 2 char
df0 = df0.withColumn("text_c", F.regexp_replace("text_c", r"\b\w{1,2}\b", ""))
# to lower case
df0 = df0.withColumn("text_c", F.lower(F.col("text_c")))
df0.toPandas().tail(5)

,text,sentiment,label,text_c
12643,"To be hones, I used to like this show and watc...",negative,0,hones used like this show and watch regul...
12644,This movie is a disgrace to the Major League F...,negative,0,this movie disgrace the major league franch...
12645,John Garfield plays a Marine who is blinded by...,positive,1,john garfield plays marine who blinded gre...
12646,"Bad plot, bad dialogue, bad acting, idiotic di...",negative,0,bad plot bad dialogue bad acting idiotic direc...
12647,I'm going to have to disagree with the previou...,negative,0,going have disagree with the previous comme...

### Lemmatization (optional)
Lemmatization is the process of reducing a word to its base or root form, which is also known as a lemma. The purpose of lemmatization is to simplify text and make it easier to analyze by grouping together different forms of the same word. For example, the words "running," "ran," and "runs" can all be reduced to the base form "run" through lemmatization. 

However, lemmatization can be a **time-consuming operation**, especially when dealing with large amounts of text data. This is because the process involves analyzing each word in a text and identifying its base form. It also requires a comprehensive understanding of the grammatical rules of a language to accurately identify the correct lemma for each word.

Despite its time-consuming nature, lemmatization can be a powerful tool in natural language processing and text analysis. It can help with tasks such as sentiment analysis, topic modeling, and text classification. When using lemmatization, it's important to use it carefully and correctly to ensure that the text is properly processed and analyzed.

In [36]:
# import spacy
# from pyspark.sql.functions import udf
# from pyspark.sql.types import StringType

# # Load the spaCy model
# nlp = spacy.load("en_core_web_sm", disable=["parser", "ner"])

# # Define a function to apply the lemmatizer to a text
# def lemmatize_text(text):
#     doc = nlp(text)
#     lemmas = [token.lemma_ for token in doc]
#     return " ".join(lemmas)

# # Define a UDF to apply the lemmatizer to a column
# lemmatize_udf = udf(lemmatize_text, StringType())

# # Apply the UDF to a DataFrame column
# df0 = df0.withColumn("text_c", lemmatize_udf(df0["text_c"]))

# # Caching must be used !!!!!!
# df0 = df0.cache()
# df0.toPandas().tail(5)

### Split the text to training and testing dataset

In [37]:
# Split the data in train and test (80%-20%)
df, test = df0.randomSplit(weights=[0.8,0.2], seed=200)
df.groupBy("label").count().show()

+-----+-----+
|label|count|
+-----+-----+
|    1| 5016|
|    0| 5138|
+-----+-----+

### Assign weights to classes

In [38]:
# Create a weight of each class
from pyspark.sql import functions as F
size = df.count()
number_of_1 = df.filter('label == 1').count()
number_of_0 = size - number_of_1
p_weight = number_of_1/ size
n_weight = number_of_0/ size
print(n_weight, p_weight)

0.5060074847350797 0.4939925152649202

In [39]:
df = df.withColumn("weight", F.when(F.col("label")==1,n_weight).otherwise(p_weight))
df.show(5)

+--------------------+---------+-----+--------------------+------------------+
|                text|sentiment|label|              text_c|            weight|
+--------------------+---------+-----+--------------------+------------------+
| Så som i himmele...| positive|    1|  som  himmelen  ...|0.5060074847350797|
| While sporadical...| negative|    0| while sporadical...|0.4939925152649202|
|'Blue Desert' may...| negative|    0|blue desert may h...|0.4939925152649202|
|'Checking Out' is...| positive|    1|checking out   ex...|0.5060074847350797|
|'Presque Rien' ('...| positive|    1|presque rien come...|0.5060074847350797|
+--------------------+---------+-----+--------------------+------------------+
only showing top 5 rows

In [40]:
from pyspark.ml.feature import HashingTF, IDF, Tokenizer, CountVectorizer
from pyspark.ml.feature import StopWordsRemover
from pyspark.ml.feature import PCA
from pyspark.ml.feature import ChiSqSelector 
from pyspark.ml.classification import LogisticRegression
from pyspark.ml.classification import LinearSVC
from pyspark.ml.classification import DecisionTreeClassifier
from pyspark.ml.classification import GBTClassifier

from pyspark.ml import Pipeline

# Data transformation

### Preprocessing pipeline
Pipelines in Spark are a powerful tool for data processing and analysis, as they enable the creation of complex data workflows that can be executed efficiently on distributed computing systems. They also simplify the data processing and analysis tasks, as they enable the chaining of multiple stages into a single workflow.

In [41]:
# Tokenize the review text
tokenizer = Tokenizer(inputCol="text_c", outputCol="words",)
# Remove stop words
remover = StopWordsRemover(inputCol=tokenizer.getOutputCol(), outputCol="filtered")
# Create a count vectorizer
countVectorizer = CountVectorizer(inputCol=remover.getOutputCol(), outputCol="rawFeatures", vocabSize=900)
# Calculate the TF-IDF
idf = IDF(inputCol=countVectorizer.getOutputCol(), outputCol="featuresIDF")
# Crate a preprocessing pipeline with 4 stages
pipeline_p = Pipeline(stages=[tokenizer,remover, countVectorizer, idf])

In [43]:
# Learn the data preprocessing model
data_model = pipeline_p.fit(df)

In [44]:
# Create a ParamMap to specify (or override) parameters for each stage.
paramMap = {
    countVectorizer.getParam("vocabSize"): 1000,     # Only keep the top 1000 words. # Overwrite the model value   
    idf.getParam("minDocFreq"): 5,                  # Only consider terms that appear in at least 5 documents
}

# Fit the pipeline model using the specified parameters.
data_model = pipeline_p.fit(df, paramMap)

In [46]:
# Transform
transformed_data = data_model.transform(df)
transformed_test = data_model.transform(test)
transformed_data.toPandas().head(5)

,text,sentiment,label,text_c,weight,words,filtered,rawFeatures,featuresIDF
0,Så som i himmelen .. as above so below.. tha...,positive,1,som himmelen above below that very spec...,0.506007,"[, , som, , himmelen, , , , above, , below, th...","[, , som, , himmelen, , , , , special, point, ...","(43.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","(0.008469568670282307, 0.0, 2.4572384294370635..."
1,While sporadically engrossing (including a fe...,negative,0,while sporadically engrossing including few ...,0.493993,"[, while, sporadically, engrossing, including,...","[, sporadically, engrossing, including, , effe...","(38.0, 0.0, 3.0, 0.0, 3.0, 0.0, 0.0, 0.0, 0.0,...","(0.0074847351039704114, 0.0, 1.842928822077797..."
2,'Blue Desert' may have had the potential to be...,negative,0,blue desert may have had the potential even ...,0.493993,"[blue, desert, may, have, had, the, potential,...","[blue, desert, may, potential, , , even, , hal...","(52.0, 2.0, 1.0, 0.0, 0.0, 0.0, 2.0, 0.0, 0.0,...","(0.010242269089643721, 1.0085643367770025, 0.6..."
3,'Checking Out' is an extraordinary film that t...,positive,1,checking out extraordinary film that towers ...,0.506007,"[checking, out, , , extraordinary, film, that,...","[checking, , , extraordinary, film, towers, fi...","(21.0, 0.0, 3.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0,...","(0.004136300978509964, 0.0, 1.8429288220777975..."
4,'Presque Rien' ('Come Undone') is an earlier w...,positive,1,presque rien come undone earlier work the i...,0.506007,"[presque, rien, come, undone, , , earlier, wor...","[presque, rien, come, undone, , , earlier, wor...","(123.0, 0.0, 6.0, 3.0, 0.0, 0.0, 0.0, 8.0, 0.0...","(0.024226905731272647, 0.0, 3.685857644155595,..."

In [47]:
# Print the sages of the pipeline
data_model.stages

[Tokenizer_491ffceaae81,
 StopWordsRemover_ef1cb2f61886,
 CountVectorizerModel: uid=CountVectorizer_ae0f1f1a0291, vocabularySize=1000,
 IDFModel: uid=IDF_b8ee20524988, numDocs=10154, numFeatures=1000]

In [48]:
# Get the vocabulary of the CountVectorizer
data_model.stages[2].vocabulary[:20]

['',
 'movie',
 'film',
 'one',
 'like',
 'good',
 'even',
 'time',
 'really',
 'see',
 'story',
 'much',
 'well',
 'get',
 'bad',
 'great',
 'also',
 'people',
 'dont',
 'first']

# Metrics for the model

In [49]:
from pyspark.mllib.evaluation import BinaryClassificationMetrics
from pyspark.mllib.evaluation import MultilabelMetrics
from pyspark.mllib.evaluation import MulticlassMetrics

def m_metrics_l(ml_model,test_data):
    predictions = ml_model.transform(test_data).cache()
    predictionAndLabels = predictions.select("label","prediction").rdd.map(lambda x: (float(x[0]), float(x[1]))).cache()
    
    # Print some predictions vs labels
    # print(predictionAndLabels.take(10))
    metrics = MulticlassMetrics(predictionAndLabels)
    
    # Overall statistics
    precision = metrics.precision(1.0)
    recall = metrics.recall(1.0)
    f1Score = metrics.fMeasure(1.0)
    print(f"Precision = {precision:.4f} Recall = {recall:.4f} F1 Score = {f1Score:.4f}")
    print("Confusion matrix \n", metrics.confusionMatrix().toArray().astype(int))

# ML Models
### Logistic Regression

In [50]:
import time
classifier = LogisticRegression(maxIter=10, regParam=0.1, featuresCol = "featuresIDF", weightCol="weight")
start = time.time()
pipeline = Pipeline(stages=[classifier])
print(f"Training started.")
model = pipeline.fit(transformed_data)
print(f"Model created in {time.time()-start:.2f}s.")
m_metrics_l(model,transformed_test)
print(f"Total time {time.time()-start:.2f}s.")

Training started.
Model created in 3.22s.

C:\Spark\spark-3.2.2-bin-hadoop3.2\python\pyspark\sql\context.py:125: FutureWarning: Deprecated in 3.0.0. Use SparkSession.builder.getOrCreate() instead.
  warnings.warn(

Precision = 0.8761 Recall = 0.8256 F1 Score = 0.8501
Confusion matrix
 [[ 983  158]
 [ 236 1117]]
Total time 20.95s.

### GBTClassifier

In [22]:
classifier = GBTClassifier(maxIter=10, featuresCol = "featuresIDF", weightCol="weight", maxDepth=6)
pipeline = Pipeline(stages=[classifier])
start = time.time()
print(f"Training started.")
model = pipeline.fit(transformed_data)
print(f"Model created in {time.time()-start:.2f}s.")
m_metrics_l(model,transformed_test)
print(f"Total time {time.time()-start:.2f}s.")

Training started.
Model created in 9.09s.
Precision = 0.8627 Recall = 0.6923 F1 Score = 0.7682
Confusion matrix
 [[ 730  175]
 [ 489 1100]]
Total time 15.42s.

### LinearSVC

In [23]:
classifier = LinearSVC(maxIter=10, regParam=0.1, featuresCol = "featuresIDF", weightCol="weight")
pipeline = Pipeline(stages=[classifier])
start = time.time()
print(f"Training started.")
model = pipeline.fit(transformed_data)
print(f"Model created in {time.time()-start:.2f}s.")
m_metrics_l(model,transformed_test)
print(f"Total time {time.time()-start:.2f}s.")

Training started.
Model created in 1.56s.
Precision = 0.8737 Recall = 0.8301 F1 Score = 0.8514
Confusion matrix
 [[ 991  161]
 [ 228 1114]]
Total time 7.77s.

### MultilayerPerceptronClassifier

In [24]:
from pyspark.ml.classification import MultilayerPerceptronClassifier
# Multilayer Perceptron Classifier for a classification task with 1000 input features, a hidden layer with 30 nodes, and 2 output classes
# The input layer must match the dimensionality of the input data currently = 1000
layers = [1000, 30, 2]

# create the trainer and set its parameters
classifier = MultilayerPerceptronClassifier(maxIter=10, layers=layers,featuresCol = "featuresIDF", blockSize=128, seed=1234)
pipeline = Pipeline(stages=[classifier])
start = time.time()
print(f"Training started.")
model = pipeline.fit(transformed_data)
print(f"Model created in {time.time()-start:.2f}s.")
m_metrics_l(model,transformed_test)
print(f"Total time {time.time()-start:.2f}s.")

Training started.
Model created in 2.25s.
Precision = 0.8620 Recall = 0.8338 F1 Score = 0.8477
Confusion matrix
 [[1000  176]
 [ 219 1099]]
Total time 8.56s.

# Features Selections
In Spark the following Feature Selectors are available
- VectorSlicer
- RFormula
- ChiSqSelector
- UnivariateFeatureSelector
- VarianceThresholdSelector

We use the ChiSqSelector to reduce the number of features from 1000 to 200. Chi-square variable selection is a technique used in statistics and machine learning to identify the most relevant features or variables in a dataset for a given classification task. It is based on the chi-square test, which is a statistical test used to determine the independence of two variables.

In [51]:
tokenizer = Tokenizer(inputCol="text_c", outputCol="words",)
remover = StopWordsRemover(inputCol=tokenizer.getOutputCol(), outputCol="filtered")
countVectorizer = CountVectorizer(inputCol=remover.getOutputCol(), outputCol="rawFeatures", vocabSize=1000)
idf = IDF(inputCol=countVectorizer.getOutputCol(), outputCol="featuresIDF")

# Select the top 200 features based on their chi-squared test value
selector =  ChiSqSelector(numTopFeatures=200, featuresCol=idf.getOutputCol(), outputCol="features", labelCol="label")
# Crate a preprocessing pipeline with 5 stages
pipeline_p = Pipeline(stages=[tokenizer,remover, countVectorizer, idf,selector])
# Learn the data preprocessing model
data_model = pipeline_p.fit(df)

### Print the selected features (words) by ChiSqSelector
To print the selected words by the ChiSqSelector in the sentiment analysis model, we can use the selectedFeatures attribute of the transformer. This attribute returns an array of the indices of the selected features, which we can map back to the original vocabulary of the CountVectorizer to get the corresponding words.

In [54]:
vocabulary = data_model.stages[2].vocabulary
selected_indexes = data_model.stages[4].selectedFeatures
selected_words = [vocabulary[i] for i in selected_indexes]
print(vocabulary)
print(selected_words)

['', 'movie', 'film', 'one', 'like', 'good', 'even', 'time', 'really', 'see', 'story', 'much', 'well', 'get', 'bad', 'great', 'also', 'people', 'dont', 'first', 'make', 'movies', 'films', 'made', 'characters', 'way', 'think', 'watch', 'many', 'never', 'seen', 'character', 'know', 'acting', 'two', 'love', 'little', 'plot', 'best', 'ever', 'life', 'show', 'better', 'end', 'still', 'say', 'something', 'man', 'scene', 'scenes', 'back', 'watching', 'real', 'thing', 'doesnt', 'nothing', 'didnt', 'actors', 'actually', 'though', 'years', 'makes', 'another', 'look', 'funny', 'going', 'find', 'lot', 'work', 'old', 'new', 'part', 'every', 'cant', 'director', 'thats', 'quite', 'things', 'want', 'pretty', 'cast', 'seems', 'around', 'got', 'young', 'take', 'fact', 'enough', 'world', 'ive', 'give', 'thought', 'however', 'long', 'right', 'big', 'horror', 'gets', 'saw', 'interesting', 'without', 'comedy', 'whole', 'least', 'isnt', 'may', 'come', 'almost', 'must', 'bit', 'theres', 'original', 'always', 'role', 'guy', 'times', 'might', 'action', 'music', 'done', 'last', 'minutes', 'far', 'feel', 'series', 'hes', 'point', 'anything', 'script', 'since', 'kind', 'performance', 'worst', 'family', 'rather', 'probably', 'sure', 'away', 'anyone', 'played', 'hard', 'trying', 'yet', 'fun', 'girl', 'woman', 'found', 'making', 'ending', 'especially', 'worth', 'believe', 'maybe', 'different', 'shows', 'comes', 'day', 'looking', 'course', 'money', 'goes', 'looks', 'place', 'watched', 'although', 'put', 'true', 'main', 'reason', 'everything', 'three', 'someone', 'wasnt', 'plays', 'actor', 'set', 'together', 'effects', 'dvd', 'book', 'job', 'screen', 'sense', 'takes', 'wife', 'night', 'instead', 'later', 'said', 'play', 'left', 'youre', 'seeing', 'seem', 'excellent', 'john', 'special', 'simply', 'idea', 'audience', 'everyone', 'shot', 'beautiful', 'year', 'high', 'american', 'half', 'kids', 'help', 'house', 'read', 'friends', 'else', 'used', 'version', 'along', 'black', 'poor', 'home', 'war', 'nice', 'fan', 'truly', 'tell', 'death', 'given', 'use', 'need', 'short', 'either', 'stupid', 'let', 'performances', 'second', 'completely', 'rest', 'dead', 'recommend', 'remember', 'camera', 'boring', 'less', 'getting', 'couple', 'mind', 'try', 'wrong', 'playing', 'sex', 'others', 'came', 'full', 'school', 'mean', 'men', 'keep', 'father', 'classic', 'face', 'next', 'start', 'hollywood', 'awful', 'couldnt', 'star', 'definitely', 'terrible', 'production', 'piece', 'small', 'dialogue', 'enjoy', 'line', 'women', 'perfect', 'name', 'gives', 'human', 'often', 'understand', 'perhaps', 'top', 'several', 'video', 'wonderful', 'guys', 'absolutely', 'went', 'early', 'lines', 'entire', 'case', 'yes', 'head', 'budget', 'style', 'supposed', 'person', 'become', 'cinema', 'waste', 'moments', 'title', 'problem', 'worse', 'children', 'felt', 'hope', 'seemed', 'mother', 'written', 'humor', 'stars', 'episode', 'certainly', 'picture', 'wants', 'becomes', 'liked', 'game', 'friend', 'already', 'loved', 'sort', 'lost', 'based', 'care', 'evil', 'youll', 'lead', 'sound', 'live', 'laugh', 'wanted', 'called', 'entertaining', 'white', 'example', 'shes', 'boy', 'days', 'direction', 'throughout', 'beginning', 'dark', 'totally', 'fans', 'wont', 'starts', 'finally', 'able', 'horrible', 'drama', 'history', 'final', 'fine', 'guess', 'son', 'flick', 'quality', 'low', 'amazing', 'killer', 'turns', 'gave', 'act', 'parts', 'writing', 'girls', 'past', 'behind', 'lives', 'eyes', 'despite', 'michael', 'killed', 'kill', 'run', 'town', 'stuff', 'kid', 'late', 'enjoyed', 'says', 'car', 'tries', 'matter', 'child', 'city', 'works', 'turn', 'actress', 'took', 'theyre', 'ill', 'directed', 'thinking', 'brilliant', 'expect', 'moment', 'sometimes', 'extremely', 'favorite', 'ones', 'heard', 'unfortunately', 'wouldnt', 'group', 'decent', 'soon', 'blood', 'fight', 'side', 'lack', 'hour', 'hell', 'told', 'overall', 'leave', 'obviously', 'heart', 'viewer', 'save', 'coming', 'art', 'strong', 'happen', 'living', 'except', 'highly', 'score', 'feeling', 'happens', 'daughter', 'close', 'taken', 'involved', 'murder', 'obvious', 'experience', 'genre', 'etc', 'violence', 'english', 'silly', 'wonder', 'looked', 'simple', 'james', 'complete', 'attempt', 'hours', 'age', 'type', 'shots', 'stop', 'reality', 'started', 'exactly', 'jack', 'hit', 'police', 'call', 'career', 'particularly', 'annoying', 'cool', 'stories', 'shown', 'david', 'hilarious', 'hand', 'including', 'opening', 'known', 'chance', 'roles', 'sad', 'saying', 'gore', 'hero', 'voice', 'crap', 'room', 'directors', 'slow', 'happened', 'robert', 'television', 'relationship', 'somewhat', 'talent', 'taking', 'whose', 'novel', 'song', 'ago', 'please', 'across', 'major', 'four', 'usually', 'released', 'alone', 'cinematography', 'jokes', 'serious', 'musical', 'sequence', 'possible', 'running', 'usual', 'god', 'order', 'none', 'seriously', 'opinion', 'due', 'lets', 'brother', 'ends', 'number', 'anyway', 'apparently', 'knew', 'cheap', 'wish', 'ridiculous', 'husband', 'important', 'view', 'word', 'level', 'turned', 'today', 'showing', 'cut', 'beyond', 'events', 'strange', 'appears', 'change', 'knows', 'five', 'documentary', 'miss', 'clearly', 'interest', 'finds', 'modern', 'female', 'talk', 'mostly', 'add', 'bring', 'within', 'problems', 'feels', 'falls', 'enjoyable', 'whether', 'scary', 'predictable', 'attention', 'talking', 'disappointed', 'whats', 'words', 'upon', 'giving', 'dialog', 'body', 'mention', 'suspense', 'ten', 'local', 'team', 'soundtrack', 'review', 'tells', 'havent', 'light', 'happy', 'supporting', 'similar', 'message', 'needs', 'surprised', 'george', 'certain', 'clear', 'huge', 'move', 'space', 'hate', 'british', 'peter', 'basically', 'minute', 'near', 'french', 'single', 'named', 'among', 'easily', 'ways', 'elements', 'somehow', 'romantic', 'buy', 'filmed', 'power', 'tried', 'arent', 'bunch', 'future', 'rock', 'youve', 'country', 'lots', 'die', 'songs', 'writer', 'wait', 'theater', 'animation', 'kept', 'gone', 'episodes', 'entertainment', 'comments', 'dull', 'means', 'tom', 'comic', 'actual', 'figure', 'doubt', 'viewers', 'earth', 'sequel', 'lady', 'thriller', 'nearly', 'sister', 'forget', 'viewing', 'fantastic', 'sets', 'brought', 'meet', 'working', 'mystery', 'monster', 'tale', 'points', 'middle', 'red', 'storyline', 'sit', 'general', 'straight', 'york', 'deal', 'realistic', 'easy', 'learn', 'rating', 'whos', 'average', 'moving', 'sorry', 'stay', 'leads', 'particular', 'fall', 'inside', 'begins', 'hear', 'write', 'avoid', 'eye', 'killing', 'needed', 'premise', 'decided', 'theme', 'using', 'imagine', 'check', 'sequences', 'greatest', 'rent', 'expected', 'form', 'subject', 'king', 'parents', 'eventually', 'became', 'western', 'previous', 'surprise', 'boys', 'doctor', 'deep', 'famous', 'lame', 'typical', 'class', 'feature', 'editing', 'memorable', 'difficult', 'oscar', 'period', 'shame', 'effort', 'island', 'question', 'follow', 'dance', 'atmosphere', 'richard', 'crime', 'situation', 'credits', 'sounds', 'release', 'reading', 'weak', 'possibly', 'remake', 'footage', 'paul', 'whatever', 'perfectly', 'material', 'leaves', 'season', 'joke', 'interested', 'sexual', 'admit', 'comment', 'imdb', 'japanese', 'hands', 'reviews', 'screenplay', 'lee', 'beauty', 'unless', 'masterpiece', 'dog', 'total', 'copy', 'fast', 'poorly', 'gay', 'filmmakers', 'quickly', 'cheesy', 'superb', 'joe', 'older', 'outside', 'background', 'air', 'believable', 'box', 'stand', 'business', 'crew', 'party', 'forced', 'vampire', 'male', 'weird', 'third', 'incredibly', 'keeps', 'meets', 'powerful', 'laughs', 'personal', 'dumb', 'battle', 'indeed', 'pay', 'meant', 'okay', 'begin', 'emotional', 'present', 'plenty', 'realize', 'various', 'german', 'street', 'development', 'break', 'ask', 'train', 'leading', 'nature', 'mess', 'laughing', 'reasons', 'note', 'features', 'twist', 'rich', 'open', 'hot', 'plus', 'otherwise', 'political', 'fails', 'brings', 'pure', 'crazy', 'scifi', 'romance', 'italian', 'following', 'appear', 'front', 'stage', 'dramatic', 'truth', 'writers', 'caught', 'spent', 'focus', 'mark', 'worked', 'van', 'clever', 'bill', 'water', 'ended', 'free', 'fairly', 'setting', 'wasted', 'towards', 'hold', 'deserves', 'badly', 'baby', 'trouble', 'attempts', 'amusing', 'unique', 'effect', 'follows', 'fighting', 'manages', 'filled', 'earlier', 'forward', 'moves', 'bored', 'cute', 'odd', 'return', 'escape', 'result', 'sees', 'created', 'talented', 'large', 'members', 'agree', 'america', 'store', 'portrayal', 'jane', 'cold', 'gun', 'social', 'cover', 'wrote', 'band', 'producers', 'nudity', 'fire', 'hair', 'cop', 'zombie', 'missing', 'died', 'considering', 'secret', 'portrayed', 'brothers', 'audiences', 'hardly', 'create', 'popular', 'society', 'era', 'dream', 'produced', 'slightly', 'casting', 'match', 'exciting', 'visual', 'apart', 'pace', 'success', 'appreciate', 'telling', 'unlike', 'waiting', 'expecting', 'william', 'girlfriend', 'former', 'creepy', 'awesome', 'directing', 'public', 'scott', 'mentioned', 'depth', 'younger', 'control', 'villain', 'acted', 'ideas', 'sweet', 'effective', 'married', 'familiar', 'successful', 'fit', 'cat', 'pathetic', 'win', 'fantasy', 'list', 'speak', 'convincing', 'flat', 'value', 'humour', 'suddenly', 'kills', 'neither', 'century', 'office', 'meaning', 'decides', 'presented', 'plain', 'dancing', 'involving', 'accent', 'prison', 'honest', 'missed', 'recently', 'bizarre', 'consider', 'choice', 'recent', 'normal', 'cause', 'potential', 'credit', 'amount', 'cartoon', 'intelligent', 'pointless', 'fake', 'frank', 'changed', 'recommended', 'books', 'walk', 'longer', 'entirely', 'mad', 'failed', 'ultimately', 'christmas', 'likes', 'company', 'alive', 'werent', 'decide', 'fear', 'gang', 'uses', 'language', 'values', 'nowhere']
['movie', 'like', 'even', 'story', 'well', 'get', 'bad', 'great', 'also', 'dont', 'make', 'acting', 'love', 'plot', 'best', 'life', 'better', 'still', 'say', 'something', 'watching', 'thing', 'doesnt', 'nothing', 'didnt', 'actually', 'years', 'cant', 'thats', 'want', 'pretty', 'young', 'world', 'horror', 'whole', 'least', 'isnt', 'may', 'theres', 'always', 'guy', 'minutes', 'series', 'point', 'anything', 'script', 'performance', 'worst', 'family', 'played', 'trying', 'fun', 'especially', 'maybe', 'different', 'shows', 'day', 'money', 'looks', 'true', 'reason', 'someone', 'wasnt', 'plays', 'effects', 'job', 'instead', 'excellent', 'idea', 'beautiful', 'half', 'else', 'poor', 'war', 'either', 'stupid', 'performances', 'completely', 'rest', 'recommend', 'boring', 'wrong', 'mean', 'classic', 'awful', 'couldnt', 'definitely', 'terrible', 'dialogue', 'perfect', 'gives', 'human', 'wonderful', 'supposed', 'become', 'waste', 'problem', 'worse', 'seemed', 'liked', 'loved', 'care', 'horrible', 'fine', 'guess', 'flick', 'low', 'amazing', 'killer', 'lives', 'kill', 'enjoyed', 'works', 'ill', 'brilliant', 'favorite', 'unfortunately', 'wouldnt', 'decent', 'hour', 'obviously', 'heart', 'save', 'strong', 'highly', 'experience', 'silly', 'wonder', 'looked', 'simple', 'complete', 'attempt', 'annoying', 'hilarious', 'saying', 'crap', 'relationship', 'none', 'seriously', 'apparently', 'cheap', 'ridiculous', 'today', 'finds', 'modern', 'enjoyable', 'predictable', 'tells', 'supporting', 'ways', 'romantic', 'tried', 'arent', 'bunch', 'dull', 'fantastic', 'brought', 'realistic', 'moving', 'sorry', 'write', 'avoid', 'killing', 'greatest', 'rent', 'lame', 'memorable', 'oscar', 'effort', 'atmosphere', 'perfectly', 'joke', 'beauty', 'unless', 'masterpiece', 'poorly', 'superb', 'powerful', 'personal', 'dumb', 'okay', 'mess', 'otherwise', 'fails', 'brings', 'spent', 'wasted', 'badly', 'unique', 'bored', 'portrayal', 'society', 'era', 'awesome', 'pathetic', 'flat', 'plain', 'pointless', 'fake', 'recommended']

### Run the algorithm usin the slected features only

In [55]:
# Transform the data
transformed_data = data_model.transform(df)
transformed_test = data_model.transform(test)

### Logistic regression
If we use ChiSqSelector to choose the top 200 features for the sentiment analysis model, we should anticipate that the model's performance may not be as high as when we use all 1000 features. The main factor causing this outcome is the reduction of information. By selecting only the top 200 features, we may discard vital information present in the remaining 800 features, which can lead to a decline in accuracy and overall performance.

In [56]:
classifier = LogisticRegression(maxIter=5, featuresCol = "features")
start = time.time()
pipeline = Pipeline(stages=[classifier])
print(f"Training started.")
model = pipeline.fit(transformed_data)
print(f"Model created in {time.time()-start:.2f}s.")
m_metrics_l(model,transformed_test)
print(f"Total time {time.time()-start:.2f}s.")

Training started.
Model created in 3.24s.

C:\Spark\spark-3.2.2-bin-hadoop3.2\python\pyspark\sql\context.py:125: FutureWarning: Deprecated in 3.0.0. Use SparkSession.builder.getOrCreate() instead.
  warnings.warn(

Precision = 0.8549 Recall = 0.8165 F1 Score = 0.8352
Confusion matrix
 [[ 974  185]
 [ 245 1090]]
Total time 19.79s.

In [57]:
from pyspark.ml.classification import MultilayerPerceptronClassifier
# Multilayer Perceptron Classifier for a classification task with 1000 input features, a hidden layer with 30 nodes, and 2 output classes
# The input layer must match the dimensionality of the input data currently = 1000
layers = [200, 8, 2]

# create the trainer and set its parameters
classifier = MultilayerPerceptronClassifier(maxIter=10, layers=layers,featuresCol = "features", blockSize=128, seed=1234)
pipeline = Pipeline(stages=[classifier])
start = time.time()
print(f"Training started.")
model = pipeline.fit(transformed_data)
print(f"Model created in {time.time()-start:.2f}s.")
m_metrics_l(model,transformed_test)
print(f"Total time {time.time()-start:.2f}s.")

Training started.
Model created in 2.11s.
Precision = 0.8604 Recall = 0.8174 F1 Score = 0.8384
Confusion matrix
 [[ 974  178]
 [ 245 1097]]
Total time 19.43s.