# Sentiment analysis model using PySpark
The task is to create a sentiment analysis model using PySpark that can classify movie reviews as either positive or negative. The input data consists of a large dataset of movie reviews that have been labeled with a sentiment score (positive or negative). The goal is to build a binary classification model that can accurately predict the sentiment of a new movie review that it has not seen before. 

The sentiment analysis model will use natural language processing (NLP) techniques to preprocess the text data, including tokenization, stopword removal, count vectorization, and TF-IDF. It will then use different machine learning algorithms, such as logistic regression, SVM, or a multilayer perceptron, to train a binary classifier on the preprocessed text features. The model will be evaluated using metrics precision, recall, F1 score, and confusion matrix. 

In the end, we show how feature selection techniques such as Chi-Square can be included in the preprocessing pipeline, and we build a logistic regression model again.

In [2]:
from pyspark import SparkContext
from pyspark.sql import SparkSession
spark = (
    SparkSession.builder
    .appName("SparkTeachingExamples")
    .master("local[1]")
    .config("spark.sql.shuffle.partitions", "1")
    .config("spark.default.parallelism", "1")
    .config("spark.ui.enabled", "false")
    .config("spark.sql.adaptive.enabled", "false")
    .getOrCreate()
)

sc = spark.sparkContext
sc.setLogLevel("ERROR")

In [3]:
import numpy as np
from pyspark.sql import functions as F

# Data preprocessing

In [4]:
tFile="data\IMDB Dataset.csv.bz2"
df0 = spark.read.csv(tFile,header=True)
df0.show(10)

+--------------------+---------+
|                text|sentiment|
+--------------------+---------+
|One of the other ...| positive|
|A wonderful littl...| positive|
|I thought this wa...| positive|
|Basically there's...| negative|
|Petter Mattei's L...| positive|
|Probably my all-t...| positive|
|I sure would like...| positive|
|This show was an ...| negative|
|Encouraged by the...| negative|
|If you like origi...| positive|
+--------------------+---------+
only showing top 10 rows

In [5]:
#Sample the data for faster model training (use the full dataset in reality)
df0 = df0.sample(0.25, seed=200)

In [6]:
# Convert sentiment to numbers positive =1, negative =0
df0 = df0.withColumn("label", F.when(F.col("sentiment")=="positive",1).otherwise(0)).cache()

In [7]:
df0.show(10, truncate=False)

+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+-----+
|text                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |sentiment|label|
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------+-----+
|One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. Forget pretty pictures painted for mainstream audiences, forget charm, forget romance...OZ doesn't mess around. The first episode I ever saw struck me as so nasty it was surreal, I couldn't say I was ready for it, but as I watched more, I developed a taste for Oz, and got accustomed to the high levels of graphic violence. Not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) Watching Oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |positive |1    |

In [8]:
# Remove html tags from text
df0 = df0.withColumn("text_c", F.regexp_replace(F.col("text"), r'<[^>]+>', ""));
# Remove non-letters
df0 = df0.withColumn("text_c", F.regexp_replace("text_c", r"[^a-zA-Z ]", ""))
# Remove words 1, 2 char
df0 = df0.withColumn("text_c", F.regexp_replace("text_c", r"\b\w{1,2}\b", ""))
# to lower case
df0 = df0.withColumn("text_c", F.lower(F.col("text_c")))
df0.toPandas().tail(5)

,text,sentiment,label,text_c
12568,John Garfield plays a Marine who is blinded by...,positive,1,john garfield plays marine who blinded gre...
12569,Robert Colomb has two full-time jobs. He's kno...,negative,0,robert colomb has two fulltime jobs hes known ...
12570,This is your typical junk comedy.<br /><br />T...,negative,0,this your typical junk comedythere are almost...
12571,"Bad plot, bad dialogue, bad acting, idiotic di...",negative,0,bad plot bad dialogue bad acting idiotic direc...
12572,I am a Catholic taught in parochial elementary...,negative,0,catholic taught parochial elementary schoo...

### Lemmatization (optional)
Lemmatization is the process of reducing a word to its base or root form, which is also known as a lemma. The purpose of lemmatization is to simplify text and make it easier to analyze by grouping together different forms of the same word. For example, the words "running," "ran," and "runs" can all be reduced to the base form "run" through lemmatization. 

However, lemmatization can be a **time-consuming operation**, especially when dealing with large amounts of text data. This is because the process involves analyzing each word in a text and identifying its base form. It also requires a comprehensive understanding of the grammatical rules of a language to accurately identify the correct lemma for each word.

Despite its time-consuming nature, lemmatization can be a powerful tool in natural language processing and text analysis. It can help with tasks such as sentiment analysis, topic modeling, and text classification. When using lemmatization, it's important to use it carefully and correctly to ensure that the text is properly processed and analyzed.

In [9]:
# import spacy
# from pyspark.sql.functions import udf
# from pyspark.sql.types import StringType

# # Load the spaCy model
# nlp = spacy.load("en_core_web_sm", disable=["parser", "ner"])

# # Define a function to apply the lemmatizer to a text
# def lemmatize_text(text):
#     doc = nlp(text)
#     lemmas = [token.lemma_ for token in doc]
#     return " ".join(lemmas)

# # Define a UDF to apply the lemmatizer to a column
# lemmatize_udf = udf(lemmatize_text, StringType())

# # Apply the UDF to a DataFrame column
# df0 = df0.withColumn("text_c", lemmatize_udf(df0["text_c"]))

# # Caching must be used !!!!!!
# df0 = df0.cache()
# df0.toPandas().tail(5)

### Split the text to training and testing dataset

In [10]:
# Split the data in train and test (80%-20%)
df, test = df0.randomSplit(weights=[0.8,0.2], seed=200)
df.groupBy("label").count().show()

+-----+-----+
|label|count|
+-----+-----+
|    1| 4984|
|    0| 5070|
+-----+-----+

### Assign weights to classes

In [11]:
# Create a weight of each class
from pyspark.sql import functions as F
size = df.count()
number_of_1 = df.filter('label == 1').count()
number_of_0 = size - number_of_1
p_weight = number_of_1/ size
n_weight = number_of_0/ size
print(n_weight, p_weight)

0.5042769047145415 0.49572309528545855

In [12]:
df = df.withColumn("weight", F.when(F.col("label")==1,n_weight).otherwise(p_weight))
df.show(5)

+--------------------+---------+-----+--------------------+-------------------+
|                text|sentiment|label|              text_c|             weight|
+--------------------+---------+-----+--------------------+-------------------+
| Domino  has been...| positive|    1| domino  has been...| 0.5042769047145415|
| It had to be You...| negative|    0|  had   you  anot...|0.49572309528545855|
| Så som i himmele...| positive|    1|  som  himmelen  ...| 0.5042769047145415|
| While sporadical...| negative|    0| while sporadical...|0.49572309528545855|
|!!!!! POSSIBLE SP...| negative|    0| possible spoiler...|0.49572309528545855|
+--------------------+---------+-----+--------------------+-------------------+
only showing top 5 rows

In [13]:
from pyspark.ml.feature import HashingTF, IDF, Tokenizer, CountVectorizer
from pyspark.ml.feature import StopWordsRemover
from pyspark.ml.feature import PCA
from pyspark.ml.feature import ChiSqSelector 
from pyspark.ml.classification import LogisticRegression
from pyspark.ml.classification import LinearSVC
from pyspark.ml.classification import DecisionTreeClassifier
from pyspark.ml.classification import GBTClassifier

from pyspark.ml import Pipeline

# Data transformation

### Preprocessing pipeline
Pipelines in Spark are a powerful tool for data processing and analysis, as they enable the creation of complex data workflows that can be executed efficiently on distributed computing systems. They also simplify the data processing and analysis tasks, as they enable the chaining of multiple stages into a single workflow.

In [14]:
# Tokenize the review text
tokenizer = Tokenizer(inputCol="text_c", outputCol="words",)
# Remove stop words
remover = StopWordsRemover(inputCol=tokenizer.getOutputCol(), outputCol="filtered")
# Create a count vectorizer
countVectorizer = CountVectorizer(inputCol=remover.getOutputCol(), outputCol="rawFeatures", vocabSize=900)
# Calculate the TF-IDF
idf = IDF(inputCol=countVectorizer.getOutputCol(), outputCol="featuresIDF")
# Crate a preprocessing pipeline with 4 stages
pipeline_p = Pipeline(stages=[tokenizer,remover, countVectorizer, idf])

In [15]:
# Learn the data preprocessing model
data_model = pipeline_p.fit(df)

In [16]:
# Create a ParamMap to specify (or override) parameters for each stage.
paramMap = {
    countVectorizer.getParam("vocabSize"): 1000,     # Only keep the top 1000 words. # Overwrite the model value   
    idf.getParam("minDocFreq"): 5,                  # Only consider terms that appear in at least 5 documents
}

# Fit the pipeline model using the specified parameters.
data_model = pipeline_p.fit(df, paramMap)

In [17]:
# Transform
transformed_data = data_model.transform(df)
transformed_test = data_model.transform(test)
transformed_data.toPandas().head(5)

,text,sentiment,label,text_c,weight,words,filtered,rawFeatures,featuresIDF
0,Domino has been widely condemned on this sit...,positive,1,domino has been widely condemned this site ...,0.504277,"[, domino, , has, been, widely, condemned, , t...","[, domino, , widely, condemned, , site, frenet...","(98.0, 2.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0,...","(0.009746879514719028, 1.0223143775115313, 0.0..."
1,It had to be You is another sign that Hollywo...,negative,0,had you another sign that hollywood runn...,0.495723,"[, , had, , , you, , another, sign, that, holl...","[, , , , , another, sign, hollywood, , running...","(28.0, 3.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0,...","(0.002784822718491151, 1.533471566267297, 0.0,..."
2,Så som i himmelen .. as above so below.. tha...,positive,1,som himmelen above below that very spec...,0.504277,"[, , som, , himmelen, , , , above, , below, th...","[, , som, , himmelen, , , , , special, point, ...","(43.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,...","(0.004276692031968553, 0.0, 2.4410200006924083..."
3,While sporadically engrossing (including a fe...,negative,0,while sporadically engrossing including few ...,0.495723,"[, while, sporadically, engrossing, including,...","[, sporadically, engrossing, including, , effe...","(38.0, 0.0, 3.0, 0.0, 3.0, 0.0, 0.0, 0.0, 0.0,...","(0.003779402260809419, 0.0, 1.8307650005193064..."
4,!!!!! POSSIBLE SPOILER !!!!!<br /><br />You`d ...,negative,0,possible spoiler youd think story involving ...,0.495723,"[, possible, spoiler, youd, think, , story, in...","[, possible, spoiler, youd, think, , story, in...","(86.0, 1.0, 6.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0,...","(0.008553384063937106, 0.5111571887557657, 3.6..."

In [18]:
# Print the sages of the pipeline
data_model.stages

[Tokenizer_9db3056e84a0,
 StopWordsRemover_9b8ed0fefb55,
 CountVectorizerModel: uid=CountVectorizer_1f0471201e82, vocabularySize=1000,
 IDFModel: uid=IDF_dcb95aeb930a, numDocs=10054, numFeatures=1000]

In [19]:
# Get the vocabulary of the CountVectorizer
data_model.stages[2].vocabulary[:20]

['',
 'movie',
 'film',
 'one',
 'like',
 'good',
 'even',
 'really',
 'time',
 'see',
 'story',
 'much',
 'well',
 'bad',
 'get',
 'also',
 'great',
 'people',
 'dont',
 'first']

# Metrics for the model

In [20]:
from pyspark.mllib.evaluation import BinaryClassificationMetrics
from pyspark.mllib.evaluation import MultilabelMetrics
from pyspark.mllib.evaluation import MulticlassMetrics

def m_metrics_l(ml_model,test_data):
    predictions = ml_model.transform(test_data).cache()
    predictionAndLabels = predictions.select("label","prediction").rdd.map(lambda x: (float(x[0]), float(x[1]))).cache()
    
    # Print some predictions vs labels
    # print(predictionAndLabels.take(10))
    metrics = MulticlassMetrics(predictionAndLabels)
    
    # Overall statistics
    precision = metrics.precision(1.0)
    recall = metrics.recall(1.0)
    f1Score = metrics.fMeasure(1.0)
    print(f"Precision = {precision:.4f} Recall = {recall:.4f} F1 Score = {f1Score:.4f}")
    print("Confusion matrix \n", metrics.confusionMatrix().toArray().astype(int))

# ML Models
### Logistic Regression

In [21]:
import time
classifier = LogisticRegression(maxIter=10, regParam=0.1, featuresCol = "featuresIDF", weightCol="weight")
start = time.time()
pipeline = Pipeline(stages=[classifier])
print(f"Training started.")
model = pipeline.fit(transformed_data)
print(f"Model created in {time.time()-start:.2f}s.")
m_metrics_l(model,transformed_test)
print(f"Total time {time.time()-start:.2f}s.")

Training started.
Model created in 5.95s.

c:\Users\dimit\miniconda3\envs\spark\Lib\site-packages\pyspark\sql\context.py:158: FutureWarning: Deprecated in 3.0.0. Use SparkSession.builder.getOrCreate() instead.
  warnings.warn(

Precision = 0.8757 Recall = 0.8270 F1 Score = 0.8506
Confusion matrix
 [[1053  154]
 [ 227 1085]]
Total time 12.35s.

### GBTClassifier

In [22]:
classifier = GBTClassifier(maxIter=10, featuresCol = "featuresIDF", weightCol="weight", maxDepth=6)
pipeline = Pipeline(stages=[classifier])
start = time.time()
print(f"Training started.")
model = pipeline.fit(transformed_data)
print(f"Model created in {time.time()-start:.2f}s.")
m_metrics_l(model,transformed_test)
print(f"Total time {time.time()-start:.2f}s.")

Training started.
Model created in 17.15s.
Precision = 0.8547 Recall = 0.7131 F1 Score = 0.7775
Confusion matrix
 [[ 854  180]
 [ 426 1059]]
Total time 21.51s.

### LinearSVC

In [23]:
classifier = LinearSVC(maxIter=10, regParam=0.1, featuresCol = "featuresIDF", weightCol="weight")
pipeline = Pipeline(stages=[classifier])
start = time.time()
print(f"Training started.")
model = pipeline.fit(transformed_data)
print(f"Model created in {time.time()-start:.2f}s.")
m_metrics_l(model,transformed_test)
print(f"Total time {time.time()-start:.2f}s.")

Training started.
Model created in 4.88s.
Precision = 0.8781 Recall = 0.8236 F1 Score = 0.8500
Confusion matrix
 [[1047  151]
 [ 233 1088]]
Total time 9.18s.

### MultilayerPerceptronClassifier

In [24]:
from pyspark.ml.classification import MultilayerPerceptronClassifier
# Multilayer Perceptron Classifier for a classification task with 1000 input features, a hidden layer with 30 nodes, and 2 output classes
# The input layer must match the dimensionality of the input data currently = 1000
layers = [1000, 30, 2]

# create the trainer and set its parameters
classifier = MultilayerPerceptronClassifier(maxIter=10, layers=layers,featuresCol = "featuresIDF", blockSize=128, seed=1234)
pipeline = Pipeline(stages=[classifier])
start = time.time()
print(f"Training started.")
model = pipeline.fit(transformed_data)
print(f"Model created in {time.time()-start:.2f}s.")
m_metrics_l(model,transformed_test)
print(f"Total time {time.time()-start:.2f}s.")

Training started.
Model created in 6.54s.
Precision = 0.8571 Recall = 0.8356 F1 Score = 0.8462
Confusion matrix
 [[1071  177]
 [ 209 1062]]
Total time 10.86s.

# Features Selections
In Spark the following Feature Selectors are available
- VectorSlicer
- RFormula
- ChiSqSelector
- UnivariateFeatureSelector
- VarianceThresholdSelector

We use the ChiSqSelector to reduce the number of features from 1000 to 200. Chi-square variable selection is a technique used in statistics and machine learning to identify the most relevant features or variables in a dataset for a given classification task. It is based on the chi-square test, which is a statistical test used to determine the independence of two variables.

In [25]:
tokenizer = Tokenizer(inputCol="text_c", outputCol="words",)
remover = StopWordsRemover(inputCol=tokenizer.getOutputCol(), outputCol="filtered")
countVectorizer = CountVectorizer(inputCol=remover.getOutputCol(), outputCol="rawFeatures", vocabSize=1000)
idf = IDF(inputCol=countVectorizer.getOutputCol(), outputCol="featuresIDF")

# Select the top 200 features based on their chi-squared test value
selector =  ChiSqSelector(numTopFeatures=200, featuresCol=idf.getOutputCol(), outputCol="features", labelCol="label")
# Crate a preprocessing pipeline with 5 stages
pipeline_p = Pipeline(stages=[tokenizer,remover, countVectorizer, idf,selector])
# Learn the data preprocessing model
data_model = pipeline_p.fit(df)

### Print the selected features (words) by ChiSqSelector
To print the selected words by the ChiSqSelector in the sentiment analysis model, we can use the selectedFeatures attribute of the transformer. This attribute returns an array of the indices of the selected features, which we can map back to the original vocabulary of the CountVectorizer to get the corresponding words.

In [26]:
vocabulary = data_model.stages[2].vocabulary
selected_indexes = data_model.stages[4].selectedFeatures
selected_words = [vocabulary[i] for i in selected_indexes]
print(vocabulary)
print(selected_words)

['', 'movie', 'film', 'one', 'like', 'good', 'even', 'really', 'time', 'see', 'story', 'much', 'well', 'bad', 'get', 'also', 'great', 'people', 'dont', 'first', 'made', 'make', 'films', 'movies', 'way', 'characters', 'think', 'many', 'character', 'seen', 'watch', 'two', 'never', 'acting', 'love', 'little', 'plot', 'best', 'know', 'show', 'ever', 'life', 'say', 'better', 'end', 'man', 'still', 'scenes', 'scene', 'something', 'doesnt', 'real', 'didnt', 'actors', 'watching', 'thing', 'years', 'back', 'makes', 'another', 'work', 'actually', 'look', 'though', 'nothing', 'lot', 'find', 'going', 'funny', 'old', 'every', 'cant', 'part', 'new', 'cast', 'quite', 'want', 'director', 'young', 'things', 'seems', 'got', 'thats', 'pretty', 'take', 'world', 'around', 'enough', 'give', 'thought', 'ive', 'horror', 'fact', 'may', 'however', 'big', 'whole', 'always', 'without', 'come', 'interesting', 'right', 'music', 'must', 'gets', 'least', 'series', 'times', 'isnt', 'saw', 'original', 'almost', 'long', 'role', 'theres', 'last', 'point', 'action', 'comedy', 'far', 'feel', 'probably', 'done', 'family', 'script', 'bit', 'hes', 'anything', 'might', 'guy', 'kind', 'rather', 'performance', 'since', 'minutes', 'away', 'worst', 'girl', 'fun', 'anyone', 'believe', 'yet', 'found', 'played', 'trying', 'although', 'put', 'woman', 'shows', 'dvd', 'sure', 'everything', 'hard', 'day', 'looking', 'goes', 'ending', 'comes', 'course', 'book', 'watched', 'especially', 'different', 'worth', 'main', 'maybe', 'wasnt', 'looks', 'money', 'making', 'reason', 'place', 'seem', 'plays', 'true', 'together', 'sense', 'set', 'said', 'screen', 'three', 'effects', 'job', 'someone', 'actor', 'special', 'play', 'takes', 'version', 'high', 'beautiful', 'later', 'excellent', 'left', 'youre', 'seeing', 'war', 'american', 'everyone', 'idea', 'instead', 'audience', 'fan', 'read', 'wife', 'year', 'night', 'black', 'john', 'house', 'shot', 'kids', 'friends', 'half', 'poor', 'given', 'used', 'else', 'along', 'short', 'performances', 'men', 'home', 'mind', 'help', 'completely', 'simply', 'need', 'try', 'star', 'wrong', 'less', 'nice', 'awful', 'father', 'truly', 'death', 'enjoy', 'mean', 'hollywood', 'recommend', 'stupid', 'camera', 'terrible', 'either', 'next', 'tell', 'use', 'let', 'second', 'couple', 'production', 'boring', 'understand', 'getting', 'school', 'start', 'remember', 'wonderful', 'rest', 'came', 'human', 'women', 'perfect', 'definitely', 'classic', 'full', 'absolutely', 'line', 'person', 'sex', 'others', 'keep', 'gives', 'stars', 'video', 'playing', 'face', 'moments', 'case', 'early', 'often', 'name', 'dead', 'budget', 'dialogue', 'couldnt', 'supposed', 'went', 'top', 'head', 'entertaining', 'perhaps', 'become', 'title', 'hope', 'guys', 'worse', 'lines', 'friend', 'lost', 'finally', 'small', 'laugh', 'children', 'written', 'style', 'liked', 'shes', 'direction', 'live', 'becomes', 'sort', 'yes', 'evil', 'several', 'picture', 'piece', 'boy', 'certainly', 'mother', 'loved', 'waste', 'fans', 'lead', 'past', 'care', 'based', 'humor', 'beginning', 'entire', 'youll', 'felt', 'cinema', 'totally', 'amazing', 'episode', 'called', 'problem', 'fine', 'final', 'example', 'wanted', 'gave', 'game', 'act', 'turn', 'horrible', 'sound', 'days', 'son', 'able', 'drama', 'quality', 'already', 'guess', 'despite', 'seemed', 'lives', 'killer', 'wont', 'dark', 'flick', 'girls', 'low', 'history', 'side', 'city', 'enjoyed', 'eyes', 'kill', 'parts', 'throughout', 'theyre', 'tries', 'car', 'works', 'michael', 'matter', 'sometimes', 'turns', 'expect', 'favorite', 'writing', 'wants', 'white', 'extremely', 'run', 'heard', 'overall', 'killed', 'directed', 'ones', 'town', 'starts', 'kid', 'group', 'viewer', 'obviously', 'took', 'stuff', 'stories', 'child', 'behind', 'decent', 'feeling', 'art', 'looked', 'late', 'ill', 'lack', 'actress', 'score', 'told', 'attempt', 'genre', 'complete', 'except', 'says', 'involved', 'serious', 'moment', 'close', 'hand', 'unfortunately', 'particularly', 'brilliant', 'highly', 'hour', 'stop', 'etc', 'wonder', 'murder', 'thinking', 'james', 'experience', 'happens', 'soon', 'hell', 'interest', 'strong', 'chance', 'blood', 'heart', 'wouldnt', 'coming', 'age', 'leave', 'career', 'fight', 'happened', 'save', 'happen', 'obvious', 'hit', 'type', 'robert', 'daughter', 'known', 'exactly', 'musical', 'word', 'roles', 'hilarious', 'living', 'police', 'saying', 'shown', 'simple', 'usually', 'silly', 'wish', 'sad', 'english', 'shots', 'major', 'including', 'hours', 'number', 'released', 'annoying', 'usual', 'slow', 'please', 'running', 'hero', 'reality', 'cinematography', 'brother', 'opening', 'across', 'cut', 'jokes', 'violence', 'somewhat', 'started', 'song', 'ends', 'attention', 'crap', 'taken', 'due', 'cool', 'order', 'scary', 'voice', 'ridiculous', 'god', 'cheap', 'sequence', 'today', 'important', 'huge', 'possible', 'knew', 'talent', 'female', 'turned', 'relationship', 'novel', 'ago', 'none', 'miss', 'apparently', 'knows', 'call', 'david', 'view', 'local', 'four', 'strange', 'opinion', 'appears', 'predictable', 'rating', 'change', 'beyond', 'bring', 'television', 'body', 'power', 'seriously', 'anyway', 'alone', 'taking', 'finds', 'whose', 'clearly', 'mostly', 'lets', 'havent', 'light', 'words', 'french', 'problems', 'disappointed', 'basically', 'british', 'tells', 'level', 'storyline', 'five', 'message', 'giving', 'theme', 'happy', 'talking', 'clear', 'episodes', 'sets', 'single', 'feels', 'jack', 'dialog', 'country', 'gore', 'supporting', 'husband', 'modern', 'review', 'lots', 'hate', 'room', 'falls', 'george', 'ten', 'space', 'future', 'arent', 'talk', 'directors', 'whats', 'parents', 'songs', 'upon', 'sequel', 'means', 'mention', 'documentary', 'needs', 'showing', 'similar', 'tried', 'fall', 'whether', 'entertainment', 'elements', 'among', 'writer', 'theater', 'effort', 'deal', 'tale', 'certain', 'youve', 'add', 'middle', 'team', 'surprise', 'enjoyable', 'imagine', 'sorry', 'dull', 'named', 'near', 'buy', 'kept', 'easily', 'actual', 'rock', 'events', 'within', 'lady', 'wait', 'monster', 'easy', 'deep', 'stay', 'ways', 'mystery', 'die', 'moving', 'suspense', 'thriller', 'check', 'hot', 'weak', 'soundtrack', 'comments', 'peter', 'viewers', 'release', 'straight', 'decided', 'earth', 'working', 'bunch', 'surprised', 'points', 'killing', 'form', 'editing', 'comic', 'sister', 'expected', 'leads', 'reviews', 'scifi', 'move', 'material', 'famous', 'nearly', 'romantic', 'viewing', 'learn', 'gone', 'brought', 'worked', 'atmosphere', 'greatest', 'general', 'typical', 'red', 'somehow', 'possibly', 'meet', 'imdb', 'write', 'filmed', 'animation', 'quickly', 'lame', 'forget', 'hear', 'forced', 'whos', 'sexual', 'interested', 'minute', 'tom', 'otherwise', 'particular', 'question', 'screenplay', 'needed', 'boys', 'rent', 'fantastic', 'sequences', 'situation', 'figure', 'whatever', 'king', 'average', 'oscar', 'richard', 'period', 'eye', 'meets', 'avoid', 'crime', 'realistic', 'feature', 'plus', 'indeed', 'begins', 'shame', 'dumb', 'comment', 'copy', 'york', 'season', 'stand', 'subject', 'premise', 'believable', 'dance', 'previous', 'became', 'credits', 'leading', 'inside', 'eventually', 'total', 'reading', 'poorly', 'truth', 'paul', 'class', 'leaves', 'box', 'difficult', 'emotional', 'sit', 'filmmakers', 'unless', 'features', 'dog', 'plenty', 'footage', 'dramatic', 'crew', 'begin', 'follow', 'using', 'doubt', 'admit', 'political', 'powerful', 'weird', 'badly', 'fast', 'beauty', 'outside', 'mark', 'background', 'setting', 'agree', 'superb', 'open', 'note', 'japanese', 'romance', 'twist', 'fails', 'okay', 'western', 'male', 'perfectly', 'cheesy', 'portrayed', 'mess', 'incredibly', 'fairly', 'doctor', 'talented', 'rich', 'memorable', 'masterpiece', 'crazy', 'create', 'wasted', 'front', 'present', 'society', 'joe', 'various', 'older', 'deserves', 'cover', 'towards', 'street', 'unique', 'joke', 'writers', 'produced', 'manages', 'result', 'nudity', 'earlier', 'ask', 'development', 'business', 'sees', 'appear', 'sounds', 'battle', 'laughs', 'odd', 'cute', 'following', 'nature', 'baby', 'era', 'fire', 'hands', 'list', 'kills', 'forward', 'ended', 'realize', 'expecting', 'caught', 'personal', 'success', 'return', 'america', 'william', 'pay', 'gay', 'water', 'acted', 'directing', 'disney', 'effect', 'party', 'follows', 'situations', 'public', 'company', 'missing', 'creepy', 'hold', 'dream', 'attempts', 'filled', 'telling', 'ideas', 'break', 'gun', 'train', 'lee', 'secret', 'brings', 'spent', 'focus', 'members', 'science', 'pure', 'stage', 'clever', 'italian', 'cop', 'died', 'biggest', 'wrote', 'meant', 'laughing', 'air', 'remake', 'third', 'office', 'hardly', 'pointless', 'brothers', 'uses', 'convincing', 'free', 'value', 'large', 'apart', 'villain', 'created', 'escape', 'pathetic', 'compared', 'sweet', 'cause', 'island', 'younger', 'respect', 'dancing', 'slightly', 'visual', 'appreciate', 'entirely', 'mentioned', 'unlike', 'potential', 'casting', 'vampire', 'waiting', 'depth', 'match', 'bill', 'girlfriend', 'band', 'alive', 'alien', 'german', 'ben', 'missed', 'christmas', 'impossible', 'bored', 'recently', 'credit', 'glad', 'familiar', 'former', 'hair', 'keeps', 'popular', 'moves', 'cold', 'questions', 'ultimately', 'reasons', 'social', 'cartoon', 'books', 'plain', 'exciting', 'speak', 'sexy', 'producers', 'basic', 'sick', 'charming', 'choice', 'awesome', 'won', 'honest', 'accent', 'married', 'solid', 'amount', 'naked', 'concept', 'violent', 'fantasy', 'singing', 'suddenly', 'fear', 'trip', 'state', 'fit', 'trouble', 'starring', 'zombie', 'longer', 'fighting', 'literally', 'portrayal', 'honestly', 'considering', 'pace', 'consider', 'walk', 'bought', 'store', 'werent', 'culture', 'rate', 'sitting', 'bother', 'scott', 'normal', 'college', 'flat']
['movie', 'like', 'even', 'story', 'well', 'bad', 'also', 'great', 'dont', 'make', 'acting', 'love', 'plot', 'best', 'life', 'say', 'better', 'still', 'doesnt', 'didnt', 'watching', 'thing', 'years', 'actually', 'nothing', 'cant', 'new', 'cast', 'want', 'young', 'thats', 'pretty', 'world', 'enough', 'horror', 'whole', 'always', 'music', 'least', 'family', 'script', 'anything', 'guy', 'performance', 'minutes', 'worst', 'shows', 'especially', 'different', 'maybe', 'wasnt', 'looks', 'money', 'reason', 'plays', 'true', 'effects', 'job', 'someone', 'beautiful', 'excellent', 'war', 'idea', 'instead', 'half', 'poor', 'else', 'performances', 'completely', 'wrong', 'awful', 'mean', 'recommend', 'stupid', 'terrible', 'either', 'boring', 'wonderful', 'rest', 'human', 'perfect', 'definitely', 'classic', 'absolutely', 'gives', 'budget', 'dialogue', 'couldnt', 'supposed', 'worse', 'lines', 'laugh', 'loved', 'waste', 'amazing', 'problem', 'fine', 'horrible', 'drama', 'guess', 'seemed', 'lives', 'dark', 'flick', 'low', 'history', 'enjoyed', 'kill', 'works', 'sometimes', 'favorite', 'decent', 'lack', 'attempt', 'complete', 'except', 'unfortunately', 'brilliant', 'highly', 'hour', 'strong', 'heart', 'save', 'word', 'hilarious', 'saying', 'simple', 'silly', 'annoying', 'crap', 'ridiculous', 'cheap', 'today', 'none', 'apparently', 'predictable', 'seriously', 'episodes', 'dialog', 'supporting', 'whats', 'tried', 'effort', 'tale', 'enjoyable', 'sorry', 'dull', 'ways', 'die', 'moving', 'weak', 'bunch', 'atmosphere', 'greatest', 'write', 'lame', 'rent', 'fantastic', 'oscar', 'meets', 'avoid', 'realistic', 'dumb', 'premise', 'believable', 'total', 'poorly', 'emotional', 'sit', 'unless', 'powerful', 'badly', 'beauty', 'superb', 'fails', 'okay', 'perfectly', 'cheesy', 'mess', 'masterpiece', 'wasted', 'cover', 'unique', 'joke', 'personal', 'brings', 'spent', 'pointless', 'pathetic', 'sweet', 'bored', 'familiar', 'plain', 'charming', 'awesome', 'solid', 'portrayal', 'honestly', 'bother', 'flat']

### Run the algorithm usin the slected features only

In [27]:
# Transform the data
transformed_data = data_model.transform(df)
transformed_test = data_model.transform(test)

### Logistic regression
If we use ChiSqSelector to choose the top 200 features for the sentiment analysis model, we should anticipate that the model's performance may not be as high as when we use all 1000 features. The main factor causing this outcome is the reduction of information. By selecting only the top 200 features, we may discard vital information present in the remaining 800 features, which can lead to a decline in accuracy and overall performance.

In [28]:
classifier = LogisticRegression(maxIter=5, featuresCol = "features")
start = time.time()
pipeline = Pipeline(stages=[classifier])
print(f"Training started.")
model = pipeline.fit(transformed_data)
print(f"Model created in {time.time()-start:.2f}s.")
m_metrics_l(model,transformed_test)
print(f"Total time {time.time()-start:.2f}s.")

Training started.
Model created in 4.77s.
Precision = 0.8563 Recall = 0.8187 F1 Score = 0.8371
Confusion matrix
 [[1045  178]
 [ 235 1061]]
Total time 9.03s.

In [29]:
from pyspark.ml.classification import MultilayerPerceptronClassifier
# Multilayer Perceptron Classifier for a classification task with 1000 input features, a hidden layer with 30 nodes, and 2 output classes
# The input layer must match the dimensionality of the input data currently = 1000
layers = [200, 8, 2]

# create the trainer and set its parameters
classifier = MultilayerPerceptronClassifier(maxIter=10, layers=layers,featuresCol = "features", blockSize=128, seed=1234)
pipeline = Pipeline(stages=[classifier])
start = time.time()
print(f"Training started.")
model = pipeline.fit(transformed_data)
print(f"Model created in {time.time()-start:.2f}s.")
m_metrics_l(model,transformed_test)
print(f"Total time {time.time()-start:.2f}s.")

Training started.
Model created in 2.79s.
Precision = 0.8467 Recall = 0.8234 F1 Score = 0.8349
Confusion matrix
 [[1055  190]
 [ 225 1049]]
Total time 6.85s.